---
abstract: 'provides Moose-like method modifiers'
author:
  - 'Shawn M Moore, C<sartak@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Method-Modifiers
no_index:
  directory:
    - inc
    - t
resources:
  homepage: https://github.com/karenetheridge/Class-Method-Modifiers/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/karenetheridge/Class-Method-Modifiers.git
    web: https://github.com/karenetheridge/Class-Method-Modifiers/tree
version: 1.10
